---
- hosts: localhost
  connection: local
  tasks:
    - ini_file:
        dest: '/home/galaxy/galaxy/config/galaxy.ini'
        section: 'app:main'
        option: 'brand'
        value: 'Epigen'
  roles:
    - role: indigo-dc.galaxycloud-tools
      galaxy_flavor: 'galaxy-epigen'
      move_datasets: false
      Galaxy_flavor_recipe_branch: 'devel'
      #create_bootstrap_user: true
